### ISSUE TITLE
ValueError: Received RT Log(s) size is not a multiple of 16: 36

### ISSUE THREAD

**Issue by bluebier** [vwout/hass-zkaccess_c3#2] opened 2023-08-27 07:33 UTC
not working

Error log:
`2023-08-25 12:41:30.170 ERROR (MainThread) [custom_components.zkaccess_c3.coordinator] Unexpected error fetching Zkaccess C3 @ 192.168.39.241:4370 data: Received RT Log(s) size is not a multiple of 16: 36
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 124, in _async_update_data
    logs = self.c3_panel.get_rt_log()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c3/core.py", line 412, in get_rt_log
    raise ValueError("Received RT Log(s) size is not a multiple of 16: %d" % message_length)
ValueError: Received RT Log(s) size is not a multiple of 16: 360`

thanks

**Comment by vwout** [comment] 2023-08-27 10:40
Thanks for the feedback @bluebier.

Some questions:
- which C3 panel are you using
- which firmware?
- is this a structural error that remains present? The number of events (>22) is relatively large. There could be a queue-up of historical events in the panel that dries out after a number of poll attempts.

**Comment by bluebier** [comment] 2023-09-01 12:37
Hello!
panel: C3-400
fw: AC Ver 5.4.3.2001 Sep 25 2019

**Comment by vwout** [comment] 2023-09-11 20:55
I finally have been able to reproduce the issue. This is an error in my zkaccess_c3 library.

**Comment by vwout** [comment] 2023-09-12 20:16
This issue should be resolved in release 0.0.2.

**Comment by bluebier** [comment] 2023-09-13 07:26
install update and re add device, not working...
Full log:
`2023-09-13 09:15:24.512 ERROR (MainThread) [custom_components.zkaccess_c3.coordinator] Unexpected error fetching ZKAccess C3 @ 192.168.39.241:4370 data: Received RT Log(s) size is not a multiple of 16: 36
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 154, in _async_update_data
    return self._poll_rt_log()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 122, in _poll_rt_log
    logs = self.c3_panel.get_rt_log()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c3/core.py", line 413, in get_rt_log
    raise ValueError("Received RT Log(s) size is not a multiple of 16: %d" % message_length)
ValueError: Received RT Log(s) size is not a multiple of 16: 36
2023-09-13 09:15:24.518 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liszt8 for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 129, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-09-13 09:15:24.537 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liszt8 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-09-13 09:15:24.555 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liszt8 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-09-13 09:15:34.790 ERROR (MainThread) [custom_components.zkaccess_c3.coordinator] Unexpected error fetching ZKAccess C3 @ 192.168.39.241:4370 data: Received RT Log(s) size is not a multiple of 16: 36
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 154, in _async_update_data
    return self._poll_rt_log()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 122, in _poll_rt_log
    logs = self.c3_panel.get_rt_log()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c3/core.py", line 413, in get_rt_log
    raise ValueError("Received RT Log(s) size is not a multiple of 16: %d" % message_length)
ValueError: Received RT Log(s) size is not a multiple of 16: 36
2023-09-13 09:15:34.801 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Liszt8' for zkaccess_c3 integration not ready yet: Received RT Log(s) size is not a multiple of 16: 36; Retrying in background
2023-09-13 09:15:34.811 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liszt8 for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 129, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-09-13 09:15:34.815 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liszt8 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-09-13 09:15:34.817 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Liszt8 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

**Comment by spaquin3** [comment] 2023-11-16 01:03
same thing for me, is the info that i have
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.zkaccess_c3.coordinator
Source: helpers/update_coordinator.py:290
Integration: C3 Access Control Panel (documentation, issues)
First occurred: 19:53:10 (5 occurrences)
Last logged: 19:54:27

Unexpected error fetching ZKAccess C3 @ 192.168.2.60:4370 data: Received RT Log(s) size is not a multiple of 16: 36
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 154, in _async_update_data
    return self._poll_rt_log()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 122, in _poll_rt_log
    logs = self.c3_panel.get_rt_log()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c3/core.py", line 413, in get_rt_log
    raise ValueError("Received RT Log(s) size is not a multiple of 16: %d" % message_length)
ValueError: Received RT Log(s) size is not a multiple of 16: 36
![zkteco](https://github.com/vwout/hass-zkaccess_c3/assets/47509313/15e6c840-1931-45d1-bc84-2be6f4e8396d)

**Comment by vwout** [comment] 2023-11-18 16:00
I haven't found the root cause of this issue yet, but commit f16dd00 might fix this.
Please test release [0.0.3](https://github.com/vwout/hass-zkaccess_c3/releases/tag/0.0.3).

**Comment by spaquin3** [comment] 2023-11-19 23:22
a did the update now im not able to load the integration i have this error 

Logger: homeassistant.config_entries
Source: config_entries.py:2077
First occurred: 18:19:47 (1 occurrences)
Last logged: 18:19:47

Error occurred loading flow for integration zkaccess_c3: cannot import name '_T' from 'homeassistant.helpers.update_coordinator' (/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py)

**Comment by vwout** [comment] 2023-11-27 21:26
I'm a little short on time, so its untested, but commit 9c054fb might fix it.

**Comment by spaquin3** [comment] 2023-12-01 23:06
juste update to 0.0.4 im now able to pass the configuration page but still a error is the log that a have 

Cette erreur provient d'une intégration personnalisée

Logger: custom_components.zkaccess_c3.coordinator
Source: helpers/update_coordinator.py:290
Integration: C3 Access Control Panel (documentation, issues)
First occurred: 18:02:40 (7 occurrences)
Last logged: 18:03:32

Unexpected error fetching ZKAccess C3 @ 192.168.2.60:4370 data: Received RT Log(s) size is not a multiple of 16: 36
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 165, in _async_update_data
    return self._poll_rt_log()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zkaccess_c3/coordinator.py", line 133, in _poll_rt_log
    logs = self.c3_panel.get_rt_log()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/c3/core.py", line 413, in get_rt_log
    raise ValueError("Received RT Log(s) size is not a multiple of 16: %d" % message_length)
ValueError: Received RT Log(s) size is not a multiple of 16: 36

**Comment by vwout** [comment] 2023-12-03 14:37
I'm not able to reproduce unfortunately.

Could you add the following to your HomeAssistant configuration (in `configuration.yaml`):
```
logger:
  logs:
    C3: debug
```
Then go to  Settings > Devices & Services and enable 'debug logging' for the ZKAccess C3 device. Interact with the C3 device (which may generate errors), optionally restart HA and disable 'debug logging' afterwards. Please send me the log.

The log should contain lines like:
```
2023-12-03 15:30:03.929 DEBUG (MainThread) [C3] Sending: aa010b0400bdac04ffdc4555
2023-12-03 15:30:04.565 DEBUG (MainThread) [C3] Receiving header: aa00c81400
2023-12-03 15:30:04.565 DEBUG (MainThread) [C3] Receiving payload: bdac04ff00000000110010000001ff008efcd42dd4e155
2023-12-03 15:30:04.566 DEBUG (MainThread) [C3] Received RT Log: 00000000110010000001ff008efcd42d
```

Alternatively, when there are no such logs, modify the file `coordinator.py` and insert the following line at line 76, just before the `if` statement:
```
        self.c3_panel.log_level(logging.DEBUG)
```
so that the code reads:
```
        self.c3_panel: C3 = C3(host, port)
        self.c3_panel.log_level(logging.DEBUG)
        if self.c3_panel.connect(password):
```
Interact with the C3 device (which may generate errors), optionally restart HA and disable 'debug logging' afterwards. Then please send me that log.

**Comment by vwout** [comment] 2023-12-03 19:34
It looks like your firmware (5.4.3.2001) replies with a different line-level protocol version. I expect `01` where yours replies `aa**02**c80000`. The contents of the response seems to be different for some replies.

My guess is that the response data `02000000320000000000000000000000000000000000000000000000c800ff0071c7d42d4d3955` is build up from:
- `02000000`: a sequence number (the number of logs messages), thus: 2
- `32000000000000000000000000000000`: 16 byte response, no idea how to decode this log
- `0000000000000000c800ff0071c7d42d`: 16 byte response with Door/Alarm Realtime Status log dated 2023-12-03 12:43:29, but without actual status information
- `4d3955`: checksum and stop byte

Some more data would allow confirming this hypothesis. Could you send a longer log, if possible including events like opening a specific door (either via a command in HomeAssistant, a button or otherwise)?

**Comment by spaquin3** [comment] 2023-12-03 23:25
[bluebier] as the same version see post
https://github.com/vwout/hass-zkaccess_c3/issues/2#issuecomment-1702679597

juste find something when im using 0.0.4 no entity or create in the integration, but if i rollback to 0.0.2 i have 16 entity that or create but they or not avaible. 
here is 3 log: 2 of 0.0.02 and 1 of  @0.0.4
[home-assistant_(version0.0.4).log](https://github.com/vwout/hass-zkaccess_c3/files/13540533/home-assistant_.version0.0.4.log)
[home-assistant_(Version0.0.2).log](https://github.com/vwout/hass-zkaccess_c3/files/13540534/home-assistant_.Version0.0.2.log)
[home-assistant_zkaccess_c3_(version0.0.2).log](https://github.com/vwout/hass-zkaccess_c3/files/13540535/home-assistant_zkaccess_c3_.version0.0.2.log)

**Comment by spaquin3** [comment] 2023-12-06 00:11
hello 
no error with 0.0.5 i have 16 entity create. is a log (debug) of some command send by home assistant. thanks you 
[home-assistant_zkaccess_c3_2023-12-06T00-05-38.908Z.log](https://github.com/vwout/hass-zkaccess_c3/files/13574187/home-assistant_zkaccess_c3_2023-12-06T00-05-38.908Z.log)

**Comment by bluebier** [comment] 2023-12-06 16:33
debugging is difficult to solve. I'm making a mini server that I connect to a panel.
please give me an address where I can send the login data

**Comment by bluebier** [comment] 2023-12-06 17:10
I have completed a lab environment![alap](https://github.com/vwout/hass-zkaccess_c3/assets/1741766/68c9462f-d7ed-4855-bbe4-0a4051df0833)
I would give you access.
email address?

**Comment by vwout** [comment] 2023-12-06 18:20
@bluebier you can contact me via hass-zkaccess_c3 at info.vwout.nl

**Comment by vwout** [comment] 2023-12-06 19:22
> hello no error with 0.0.5 i have 16 entity create. is a log (debug) of some command send by home assistant. thanks you [home-assistant_zkaccess_c3_2023-12-06T00-05-38.908Z.log](https://github.com/vwout/hass-zkaccess_c3/files/13574187/home-assistant_zkaccess_c3_2023-12-06T00-05-38.908Z.log)

Thanks a lot @spaquin3!

It looks like my initial guess was wrong. The rt log response is not two 16-byte message with a header, but a one or more 36-byte messages, e.g.:
```02000000320000000000000000000000000000000000000000000000c800ff000d5ad62d``` (one message)
or
```00000000300000000000000000000000000000000000000000000000c8010d02785ad62d00000000300000000000000000000000000000000000000000000000c8010d02795ad62d00000000300000000000000000000000000000000000000000000000c8010c027a5ad62d00000000300000000000000000000000000000000000000000000000c8010c027d5ad62d00000000300000000000000000000000000000000000000000000000c8010d027e5ad62d``` (fivemessages)

Only thing is that besides the timestamp, not much seems to change.
Would you be able to perform actions, e.g. open a door via HomeAssistant, close the door, open the door with a button or a card read, etc ... each with at least a minute in between the actions and a log at what time you performed what action?
With such info it might be possible to reverse engineer the data structure - if the request I'm sending is functional at all for the firmware your unit has...

**Closed** 2023-12-15 21:29 UTC
